name: "layoutlm_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 4
input [
    {
        name: "input_ids",
        data_type: TYPE_INT64,
        dims: [512]   
    },
    {
        name: "attention_mask",
        data_type: TYPE_INT64,
        dims: [512]
    },
    {
        name: "token_type_ids",
        data_type: TYPE_INT64,
        dims: [512]
    },
    {
        name: "bbox"
        data_type: TYPE_INT64,
        dims: [512, 4]
    }
]
output [
    {
        name: "output",
        data_type: TYPE_FP32,
        dims: [512, 2]
    }
]